close;clear;clc;
%定义控制界面
Hf=figure('Units','characters',...
          'MenuBar','none',...
          'Name','PIA&CMS TEST SYSTEM',...
          'NumberTitle','off',...
          'Position',[10 5 180 45],...
          'HandleVisibility','callback');


% optical instruments label
Hm=uimenu(Hf,'Label','Instruments');
Hm1=uimenu(Hm,'Label','Connect');
Hm2=uimenu(Hm,'Label','DisConnect');

%open instruments
uimenu(Hm1,'Label','IV_test(K2612A)',...
    'Callback','open_K2612A');%open K2612A
uimenu(Hm1,'Label','Lock-in Amplifier',...
    'Callback','g_Lockin=gpib(''NI'',0,8);fopen(g_Lockin);set(Hp_Lockin,''Foregroundcolor'',''r'');');
uimenu(Hm1,'Label','Spectrograph & Monochromator',...
    'Callback','Open_spectrograph');
uimenu(Hm1,'Label','Temperature Controller',...
    'Callback','g_Tcontroller=gpib(''NI'',0,11);fopen(g_Tcontroller);set(Hp_Tcontroller,''Foregroundcolor'',''r'');');
uimenu(Hm1,'Label','Waveform Generator',...
    'Callback','g_Wgenerator=gpib(''NI'',0,10);fopen(g_Wgenerator);set(Hp_Wgenerator,''Foregroundcolor'',''r'');');

%close instruments
uimenu(Hm2,'Label','IV_test(K2612A)',...
    'Callback','fclose(g_K2612A);delete(g_K2612A);clear g_K2612A;set(Hp_iv,''Foregroundcolor'',''k'');');%close K2612A
uimenu(Hm2,'Label','Lock-in Amplifier',...
    'Callback','fclose(g_Lockin);delete(g_Lockin);clear g_Lockin;set(Hp_Lockin,''Foregroundcolor'',''k'');');  
uimenu(Hm2,'Label','Spectrograph & Monochromator',...
    'Callback','Close_spectrograph');
uimenu(Hm2,'Label','Temperature Controller',...
    'Callback','fclose(g_Tcontroller);delete(g_Tcontroller);clear g_Tcontroller;set(Hp_Tcontroller,''Foregroundcolor'',''k'');');  
uimenu(Hm2,'Label','Waveform Generator',...
    'Callback','fclose(g_Wgenerator);delete(g_Wgenerator);clear g_Wgenerator;set(Hp_Wgenerator,''Foregroundcolor'',''k'');');

%%%axis%%%%
Ha_IW=axes(...
          'Parent',Hf,...
          'Units','normalized',...
          'Position',[0.64 0.58 0.35 0.36 ],...
          'Box','on' );
set(Ha_IW,'Color',[0.5 0.5 0.5]);
%set(get(Ha_IW,'Title'),'String','Reference Transmission','FontSize',10,'FontWeight','bold');
set(get(Ha_IW,'XLabel'),'String','Energy/eV','FontSize',10,'FontWeight','bold');
set(get(Ha_IW,'YLabel'),'String','Photocurrent(A)','FontSize',10,'FontWeight','bold');

Ha_QW=axes(...
          'Parent',Hf,...
          'Units','normalized',...
          'Position',[0.64 0.1 0.35 0.36 ],...
          'Box','on' );
set(Ha_QW,'Color',[0.5 0.5 0.5]);
%set(get(Ha_QW,'Title'),'String','Quantum Efficiency','FontSize',10,'FontWeight','bold');
set(get(Ha_QW,'XLabel'),'String','Energy/eV','FontSize',10,'FontWeight','bold');
set(get(Ha_QW,'YLabel'),'String','10^4\DeltaT/T','FontSize',10,'FontWeight','bold');

%定义版权面板
uicontrol(Hf,...
          'Units','normalized',...
          'BackgroundColor',get(Hf,'Color'),...
          'Position',[0.15 0.01 0.7 0.03],...
          'String','Copyright 2011, Department of Electrinic Engineering, CUHK. Designed by Haihua Xu.',...
          'FontWeight','bold',...
          'FontSize',9,...
          'ForegroundColor',[0 0 0],...
          'Style','text' );     
      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%Start Wgenerator%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Hp_Wgenerator=uipanel(Hf,...
          'Units','normalized',...
          'BackgroundColor',[0.95 0.95 0.95],...
          'Title','Waveform Generator',...
          'TitlePosition','centertop',...
          'Clipping','on',...
          'FontWeight','bold',...
          'FontSize',11,...
          'ForegroundColor',[0 0 0],...
          'Position',[0.02 0.84  0.55 0.13]);
uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Wgenerator,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.02 0.6 0.35 0.3],...
          'String','Function',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
 
Hc_function=uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'Position',[0.15 0.8 0.17 0.2],...
          'HorizontalAlignment','left',...
          'String',{'Sinusoid','Square','Pulse',},...
          'Value',1,...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','popupmenu');
uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Wgenerator,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.35 0.6 0.35 0.3],...
          'String','Freq',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
Hc_frequency=uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Position',[0.43 0.6 0.07 0.3],...
          'String','1',...
          'Style','edit' );
uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Wgenerator,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.5 0.6 0.35 0.3],...
          'String','kHz',...
          'FontSize',10,...
          'ForegroundColor',[0 0 0],...
          'FontWeight','bold',...
          'Style','text');

uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Wgenerator,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.57 0.6 0.35 0.3],...
          'String','Vpp',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
Hc_amplitude=uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Position',[0.64 0.6 0.07 0.3],...
          'String','1',...
          'Style','edit' );
uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Wgenerator,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.72 0.6 0.1 0.3],...
          'String','V',...
          'FontSize',10,...
          'ForegroundColor',[0 0 0],...
          'FontWeight','bold',...
          'Style','text');

uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Wgenerator,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.76 0.6 0.2 0.3],...
          'String','Offset',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
Hc_amplitude=uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Position',[0.85 0.6 0.07 0.3],...
          'String','1',...
          'Style','edit' );
uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Wgenerator,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.93 0.6 0.05 0.3],...
          'String','V',...
          'FontSize',10,...
          'ForegroundColor',[0 0 0],...
          'FontWeight','bold',...
          'Style','text');
Hp_output_on=uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'Callback','waveform_output',...
          'Position',[0.65 0.16 0.15 0.35],...
          'FontSize',10,...
          'FontWeight','bold',...
          'String','Output On',...
          'Style','pushbutton' );
Hp_output_off=uicontrol(Hp_Wgenerator,...
          'Units','normalized',...
          'Callback','fprintf(g_Wgenerator,''OUTP OFF'');set(Hp_output_off,''Foregroundcolor'',''b'');set(Hp_output_on,''Foregroundcolor'',''black'');',...
          'Position',[0.85 0.16 0.15 0.35],...
          'FontSize',10,...
          'FontWeight','bold',...
          'String','Output Off',...
          'Style','pushbutton' );

%%%%%%%%%%%%%%%%%%%%End Wgenerator%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%Tcontroller%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Hp_Tcontroller=uipanel(Hf,...
          'Units','normalized',...
          'BackgroundColor',[0.95 0.95 0.95],...
          'Title','Temperature Controller',...
          'TitlePosition','centertop',...
          'Clipping','on',...
          'FontWeight','bold',...
          'FontSize',11,...
          'ForegroundColor',[0 0 0],...
          'Position',[0.02 0.71  0.55 0.1]);
uicontrol(Hp_Tcontroller,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Tcontroller,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.01 0.43  0.3 0.5],...
          'String','Sample V/T Display',...
          'FontWeight','bold',...
          'Style','text' ); 
Hc_sample_voltage=uicontrol(Hp_Tcontroller,...
          'Units','normalized',...
          'BackgroundColor',get(Hf,'Color'),...
          'Position',[0.25 0.45 0.12 0.5],...
          'HorizontalAlignment','center',...
          'String','N.A.',...
          'ForegroundColor',[1 0 0],...
          'FontWeight','bold',...
          'Style','text');
uicontrol(Hp_Tcontroller,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Tcontroller,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.38 0.43  0.3 0.5],...
          'String','V',...
          'FontWeight','bold',...
          'Style','text' ); 
Hc_sample_temperature=uicontrol(Hp_Tcontroller,...
          'Units','normalized',...
          'BackgroundColor',get(Hf,'Color'),...
          'Position',[0.45 0.45 0.12 0.5],...
          'HorizontalAlignment','center',...
          'String','N.A.',...
          'ForegroundColor',[1 0 0],...
          'FontWeight','bold',...
          'Style','text');
uicontrol(Hp_Tcontroller,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Tcontroller,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.58 0.43  0.3 0.5],...
          'String','K',...
          'FontWeight','bold',...
          'Style','text' ); 
  uicontrol(Hp_Tcontroller,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Tcontroller,'BackgroundColor'),...
          'Callback','Sample_display',...
          'Position',[0.64 0.45 0.12 0.6],...
          'String','Display',...
          'FontWeight','bold',...
          'Style','pushbutton' );
  Hp_display_status=uicontrol(Hp_Tcontroller,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Tcontroller,'BackgroundColor'),...
          'Callback','Stop_Sample_display',...
          'Position',[0.8 0.45 0.15 0.6],...
          'String','Stop display',...
          'FontWeight','bold',...
          'Value',1,...
          'Style','pushbutton' );
%%%%%%%%%%%%%%%%%%%%End Tcontroller%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%Lock in Amplifier%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Hp_Lockin=uipanel(Hf,...
          'Units','normalized',...
          'BackgroundColor',[0.95 0.95 0.95],...
          'Title','Lock-in Amplifier',...
          'TitlePosition','centertop',...
          'Clipping','on',...
          'FontWeight','bold',...
          'FontSize',11,...
          'ForegroundColor',[0 0 0],...
          'Position',[0.02 0.4  0.55 0.28]);
  %R
 uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.1 0.89 0.12 0.1],...
          'String','R',...
          'FontSize',10,...
          'FontWeight','bold',...
          'Style','text');
 Hc_val_vlg=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hf,'Color'),......
          'HorizontalAlignment','center',...
          'Position',[0.15 0.89 0.14 0.1],...
          'String','N.A.',...
          'FontAngle','italic',...    
          'FontSize',10,...
          'ForegroundColor',[1 0 0],...
          'FontWeight','bold',...
          'Style','text');
Hc_unit=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),......
          'HorizontalAlignment','center',...
          'Position',[0.3 0.86 0.06 0.13],...
          'String','mV',... 
          'FontSize',10,...
          'FontWeight','bold',...
          'Style','text');

%degree
uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.45 0.89 0.12 0.1],...
          'String','θ',...
          'FontSize',10,...
          'FontWeight','bold',...
          'Style','text');
 Hc_val_deg=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hf,'Color'),......
          'HorizontalAlignment','center',...
          'Position',[0.5 0.89 0.14 0.1],...
          'String','N.A.',...
          'FontAngle','italic',...    
          'FontSize',10,...
          'ForegroundColor',[1 0 0],...
          'FontWeight','bold',...
          'Style','text');
  uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'Position',[0.65 0.86 0.06 0.13],...
          'HorizontalAlignment','left',...
          'String','deg',...
          'FontSize',10,...
          'ForegroundColor',[0 0 0],...
          'FontWeight','bold',...
          'Style','text');
      
 %Initial set
 Hc_initial_set=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'Callback','Initial_set',...
          'Position',[0.78 0.87 0.15 0.16],...
          'FontSize',10,...
          'FontWeight','bold',...
          'String','Lock_in_Initial Set',...
          'Style','pushbutton' );
 
 %sensitivity   
 uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.01 0.49 0.35 0.3],...
          'String','Sensitivity',...
          'FontAngle','italic',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
 
Hc_sensitivity=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'Callback','sensitivity_select',...
          'Position',[0.15 0.51 0.15 0.3],...
          'HorizontalAlignment','left',...
          'String',{'2 nV/fA','5 nV/fA','10 nV/fA','20 nV/fA','50 nV/fA','100 nV/fA','200 nV/fA','500 nV/fA','1 uV/pA','2 uV/pA','5 uV/pA','10 uV/pA','20 uV/pA','50 uV/pA','100 uV/pA','200 uV/pA','500 uV/pA','1 mV/nA','2 mV/nA','5 mV/nA','10 mV/nA','20 mV/nA','50 mV/nA','100 mV/nA','200 mV/nA'},...
          'Value',17,...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','popupmenu');
 
 %Reserve
 uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.32 0.49 0.35 0.3],...
          'String','Reserve',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
 
Hc_reserve=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'Callback','reserve_select',...
          'Position',[0.43 0.51 0.17 0.3],...
          'HorizontalAlignment','left',...
          'String',{'Low noise','Normal','High reserve',},...
          'Value',1,...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','popupmenu');
 %Ref. phase
 uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.63 0.49 0.35 0.3],...
          'String','Ref. phase',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
 
Hc_phase=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Position',[0.77 0.68 0.08 0.12],...
          'String','0',...
          'Style','edit' );
uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'Callback','phase_set=get(Hc_phase,''String'');fprintf(g_Lockin,[''phas'',phase_set])',...
          'Position',[0.85 0.68 0.08 0.12],...
          'FontSize',8,...
          'FontWeight','bold',...
          'String','set',...
          'Style','pushbutton' );

uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'Callback','fprintf(g_Lockin,''phas?'');s=fscanf(g_Lockin);fprintf(g_Lockin,[''phas '',num2str(str2num(s)+1)]);',...
          'Position',[0.93 0.75 0.06 0.1],...
          'FontSize',11,...
          'FontWeight','bold',...
          'String','+',...
          'Style','pushbutton' );
uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'Callback','fprintf(g_Lockin,''phas?'');s=fscanf(g_Lockin);fprintf(g_Lockin,[''phas '',num2str(str2num(s)-1)]);',...
          'Position',[0.93 0.65 0.06 0.1],...
          'FontSize',11,...
          'FontWeight','bold',...
          'String','-',...
          'Style','pushbutton' );
      
 %Input
 uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.03 0.30 0.35 0.3],...
          'String','Input',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
 
Hc_input=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'Callback','input_select',...
          'Position',[0.15 0.32 0.15 0.3],...
          'HorizontalAlignment','right',...
          'String',{'      A','     A-B','I(1M gain)','I(100M gain)'},...
          'Value',1,...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','popupmenu');
      
uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.32 0.3 0.35 0.3],...
          'String','Ground',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
 
Hc_ground=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'Callback','ground_select',...
          'Position',[0.43 0.32 0.17 0.3],...
          'HorizontalAlignment','right',...
          'String',{'    Float','    Ground'},...
          'Value',1,...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','popupmenu');
 uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.63 0.31 0.35 0.3],...
          'String','Couple mode',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
 Hc_couple=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'Callback','couple_select',...
          'Position',[0.81 0.32 0.13 0.3],...
          'HorizontalAlignment','right',...
          'String',{'    AC','    DC'},...
          'Value',1,...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','popupmenu');
      
 uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.01 0.3 0.35 0.1],...
          'String','Ref. source',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
 Hc_ref_source=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'Callback','ref_source_select',...
          'Position',[0.16 0.32 0.14 0.1],...
          'HorizontalAlignment','right',...
          'String',{'Internal','External'},...
          'Value',1,...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','popupmenu');

%osc harm
uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.32 0.3 0.35 0.1],...
          'String','Osc.harm',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
Hc_osc_harm=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Position',[0.45 0.28 0.08 0.12],...
          'String','1',...
          'Style','edit' );
uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'Callback','harm_set=get(Hc_osc_harm,''String'');fprintf(g_Lockin,[''harm'',harm_set])',...
          'Position',[0.53 0.28 0.06 0.12],...
          'FontSize',8,...
          'FontWeight','bold',...
          'String','set',...
          'Style','pushbutton' );

%ref. trigger
uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.63 0.3 0.35 0.1],...
          'String','Ref.trigger',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
Hc_ref_trigger=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'Callback','trigger_select',...
          'Position',[0.78 0.32 0.15 0.1],...
          'HorizontalAlignment','right',...
          'String',{'   sine','rising edge','falling edge'},...
          'Value',1,...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','popupmenu');
 
%time setup     
 uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.01 0.08 0.35 0.1],...
          'String','Time const',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
 
Hc_time_constant=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'Callback','time_constant_select',...
          'Position',[0.16 0.1 0.15 0.1],...
          'HorizontalAlignment','left',...
          'String',{'10 us','30 us','100 us','300 us','1 ms','3 ms','10 ms','30 ms','100 ms','300 ms','1 s','3 s','10 s','30 s','100 s','300 s','1 ks','3 ks','10 ks','30 ks'},...
          'Value',1,...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','popupmenu');
 
%Slope    
 uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.32 0.08 0.35 0.1],...
          'String','Slope',...
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
 
Hc_slope=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'Callback','slope_select',...
          'Position',[0.4 0.1 0.15 0.1],...
          'HorizontalAlignment','left',...
          'String',{'6 dB/oct','12 dB/oct','18 dB/oct','24 dB/oct'},...
          'Value',1,...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','popupmenu');

 %Display   
 uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_Lockin,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.65 0.08 0.35 0.1],...
          'String','Display',...
          'FontAngle','italic',...    
          'FontSize',10,...
          'ForegroundColor',[0 0 1],...
          'FontWeight','bold',...
          'Style','text');
 
Hc_display=uicontrol(Hp_Lockin,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'Callback','display_select',...
          'Position',[0.75 0.1 0.1 0.1],...
          'HorizontalAlignment','left',...
          'String',{' X-Y',' R-θ'},...
          'Value',2,...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','popupmenu');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%END Lock-in%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%Monochromator%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Hp_spetrograph=uipanel(Hf,...
          'Units','normalized',...
          'BackgroundColor',[0.95 0.95 0.95],...
          'Title','Charge Modulation Spectroscopy',...
          'TitlePosition','centertop',...
          'Clipping','on',...
          'FontWeight','bold',...
          'FontSize',11,...
          'ForegroundColor',[0 0 0],...
          'Position',[0.02 0.12  0.55 0.25]);

% display  wavelength
uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'Position',[0.02 0.88 0.35 0.12],...
          'HorizontalAlignment','left',...
          'String','Wavelength (nm)',...
          'FontSize',10,...
          'FontWeight','bold',...
          'Style','text'); 
Hc_val_wavelength=uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hf,'Color'),...
          'Position',[0.25 0.88 0.16 0.12],...
          'HorizontalAlignment','center',...
          'String','N.A.',...
          'FontSize',10,...
          'ForegroundColor',[1 0 0],...
          'FontWeight','bold',...
          'Style','text');

 % filter select
 uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'Position',[0.43 0.88 0.18 0.12],...
          'HorizontalAlignment','left',...
          'String','Filter',...
          'FontSize',10,...
          'FontWeight','bold',...
          'Style','text');
 Hc_filter_number=uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hf,'Color'),...
          'Position',[0.51 0.88 0.16 0.12],...
          'HorizontalAlignment','center',...
          'String','N.A.',...
          'FontSize',10,...
          'ForegroundColor',[1 0 0],...
          'FontWeight','bold',...
          'Style','text');
%Detector select
 uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'Position',[0.68 0.88 0.18 0.12],...
          'HorizontalAlignment','left',...
          'String','Detector',...
          'FontSize',10,...
          'FontWeight','bold',...
          'Style','text');
 Hc_detector=uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hf,'Color'),...
          'Position',[0.8 0.88 0.19 0.12],...
          'HorizontalAlignment','center',...
          'String','N.A.',...
          'FontSize',10,...
          'ForegroundColor',[1 0 0],...
          'FontWeight','bold',...
          'Style','text');
 

% wavelength scan
uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.02 0.66 0.12 0.15],...
          'FontWeight','bold',...
          'String','Start (nm)',...
          'Style','text' );
Hc_Wstart=uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Position',[0.15 0.66 0.12 0.15],...
          'String','400',...
          'Style','edit' );
uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.02 0.48 0.20 0.15],...
          'FontWeight','bold',...
          'String','Stop (nm)',...
          'Style','text' );
      
Hc_Wstop=uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Position',[0.15 0.48 0.12 0.15],...
          'String','1100',...
          'Style','edit' );
uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.02 0.29 0.20 0.15],...
          'FontWeight','bold',...
          'String','Step (nm)',...
          'Style','text' );
Hc_Wstep=uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Position',[0.15 0.3 0.12 0.15],...
          'String','10',... 
          'Style','edit' );

 % Return to     
 uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.3 0.66 0.20 0.15],...
          'FontWeight','bold',...
          'String','Return to (nm)',...
          'Style','text' );  
Hc_Wreturn=uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Position',[0.5 0.66 0.12 0.15],...
          'String','500',...
          'Style','edit' );
% Waiting time 
uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.3 0.48 0.20 0.15],...
          'FontWeight','bold',...
          'String','waiting time (s)',...
          'Style','text' );  
Hc_Wtime=uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Position',[0.5 0.49 0.12 0.15],...
          'String','180',...
          'Style','edit' );
% Sampling cycles
uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'HorizontalAlignment','left',...
          'Position',[0.3 0.29 0.20 0.15],...
          'FontWeight','bold',...
          'String','Sampling cycle',...
          'Style','text' );  
Hc_Scycle=uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Position',[0.5 0.3 0.12 0.15],...
          'String','1000',...
          'Style','edit' );      

  uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'Callback','Return_to',...
          'Position',[0.65 0.66 0.12 0.16],...
          'String','Return',...
          'FontSize',9,...
          'FontWeight','bold',...
          'Style','pushbutton' );
   uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'Callback','Stop_wavelength_scan',...
          'Position',[0.8 0.66 0.1 0.16],...
          'String','Stop',...
          'FontWeight','bold',...
          'FontSize',9,...
          'Style','pushbutton' );
 uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'Callback','cla(Ha_IW),cla(Ha_QW);Backgroud_Scan',...
          'Position',[0.65 0.48 0.13 0.16],...
          'String','Scan',...
          'FontWeight','bold',...
          'FontSize',9,...
          'Style','pushbutton' );
 uicontrol(Hp_spetrograph,...
          'Units','normalized',...
          'BackgroundColor',get(Hp_spetrograph,'BackgroundColor'),...
          'Callback','bg_save',...
          'Position',[0.79 0.48 0.1 0.18],...
          'String','Save',...
          'FontWeight','bold',...
          'Style','pushbutton' );


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%END Monochromator%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


