sensitivity_num=get(Hc_sensitivity,'Value');
switch sensitivity_num
    case 1
        fprintf(g_Lockin,'sens 0');
    case 2
        fprintf(g_Lockin,'sens 1');
    case 3
        fprintf(g_Lockin,'sens 2');
    case 4
        fprintf(g_Lockin,'sens 3');
    case 5
        fprintf(g_Lockin,'sens 4');
    case 6
        fprintf(g_Lockin,'sens 5');
    case 7
        fprintf(g_Lockin,'sens 6');
    case 8
        fprintf(g_Lockin,'sens 7');
    case 9
        fprintf(g_Lockin,'sens 8');
    case 10
        fprintf(g_Lockin,'sens 9');
    case 11
        fprintf(g_Lockin,'sens 10');
    case 12
        fprintf(g_Lockin,'sens 11');
    case 13
        fprintf(g_Lockin,'sens 12');
    case 14
        fprintf(g_Lockin,'sens 13');
    case 15
        fprintf(g_Lockin,'sens 14');
    case 16
        fprintf(g_Lockin,'sens 15');
    case 17
        fprintf(g_Lockin,'sens 16');
    case 18
        fprintf(g_Lockin,'sens 17');
    case 19
        fprintf(g_Lockin,'sens 18');
    case 20
        fprintf(g_Lockin,'sens 19');
    case 21
        fprintf(g_Lockin,'sens 20');
    case 22
        fprintf(g_Lockin,'sens 21');
    case 23
        fprintf(g_Lockin,'sens 22');
    case 24
        fprintf(g_Lockin,'sens 23');
    case 25
        fprintf(g_Lockin,'sens 24');
end